name: Build PR when labeled

on:
  pull_request:
    types: [ labeled ]

env:
  TRIGGER_LABEL: trigger-build

jobs:
  remove-label:
    uses: canonical/inference-snaps-dev/.github/workflows/remove-label.yaml@refact-reusable
    with:
      label: ${{ env.TRIGGER_LABEL }}

  build-and-publish:
    if: github.event.label.name == ${{ env.TRIGGER_LABEL }}
    uses: canonical/inference-snaps-dev/.github/workflows/build-publish-snap.yaml@refact-reusable
    with:
      init-build-script: 'prepare-models.sh'
      # Publish to a channel with the pr number in it
      publish-channel: latest/edge/pr-${{ github.event.pull_request.number }} # Add track if needed, e.g., 24/latest/edge/pr-#
    secrets:
      store-credentials: ${{ secrets.STORE_LOGIN }}
