name: Build PR when labeled

on:
  # Use pull_request_target to grant write access to the PR
  # This event runs from the context of the base of the PR rather than its head, affecting the default checkout behavior
  pull_request: # TODO change to pull_request_target after testing
    types: [ labeled ]

jobs:
  trigger:
    name: Trigger build and remove label
    uses: canonical/inference-snaps-dev/.github/workflows/trigger-by-label.yaml@IENG-1891-refactor-ci

  build-and-publish:
    name: Build and publish snap
    needs: trigger
    uses: canonical/inference-snaps-dev/.github/workflows/build-publish-snap.yaml@IENG-1891-refactor-ci
    with:
      # Checkout head of PR, not the base which is the context of this workflow
      build-sha: ${{ github.event.pull_request.head.sha }}
      # Publish to a channel with the pr number in it
      publish-channel: latest/edge/pr-${{ github.event.pull_request.number }} # Add track if needed, e.g., 24/latest/edge/pr-#
    secrets:
      store-credentials: ${{ secrets.STORE_LOGIN }}
